"""Añadir columna registration_date

Revision ID: ca7a2068ab6f
Revises: 8b2ad962e3ee
Create Date: 2025-03-12 09:44:56.536208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca7a2068ab6f'
down_revision = '8b2ad962e3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###
